#! /usr/bin/zsh

[[ $USERNAME != "root" ]] && echo please run as root && exit 1
( [[ -z $NONROOTUSER ]] || [[ -z $EDITOR ]] ) && echo please set NONROOTUSER and EDITOR && exit 1
( [[ $# -lt 1 ]] || [[ $@ =~ ".*/proc/self/fd/.+" ]] ) && echo argument error && exit 1
( [[ $# -eq 1 ]] && ! [[ -d $(dirname $@) ]] ) && echo No such dir : $(dirname $@) && exit 1

doaseditdir="/tmp/doasedit" &&
if [[ -d $doaseditdir ]]; then
	[[ $(ls -l $(dirname $doaseditdir) | grep $(basename $doaseditdir) | awk '{ print $1 $3 $4}') != "drwx--x---root$NONROOTUSER" ]] && echo improper permissions : $doaseditdir && exit 1
else
	mkdir -m 710 $doaseditdir &&
	chgrp $NONROOTUSER $doaseditdir
fi

declare -a file temp_file mod_time1 mod_time2 &&
for i in $(seq 1 $#)
do
	arg="${@[i]}" &&
	if [[ $arg[1] == "/" ]]; then
		file[i]="$arg"
	else
		file[i]="$PWD/$arg"
	fi &&

	temp_file[i]="$doaseditdir/$(basename ${file[i]})__$(echo "${$}_$i_$RANDOM_$(date)" | md5sum | awk '{ print $1 }')" &&

	if [[ -f ${file[i]} ]]; then
		install -g $NONROOTUSER -m 660 ${file[i]} ${temp_file[i]} &&
		mod_time1[i]="$(stat -c %y ${temp_file[i]})"
	elif [[ -d $(dirname ${temp_file[i]}) ]]; then
		touch ${temp_file[i]} &&
		mod_time1[i]="$(stat -c %y ${temp_file[i]})"
	else
		echo No such dir : $(dirname ${file[i]}) &&
		temp_file[i]= &&
		mod_time1[i]= &&
		continue
	fi
done

doas -u $NONROOTUSER /usr/bin/$EDITOR ${temp_file[@]} &&

for i in $(seq 1 $#)
do
	[[ $temp_file[i] == "" ]] && continue

	mod_time2[i]="$(stat -c %y ${temp_file[i]})" &&
	if [[ ${mod_time1[i]} != ${mod_time2[i]} ]]; then
		cat ${temp_file[i]} > ${file[i]} &&
		echo Modified ${file[i]}
	else
		echo ${file[i]} not modified
	fi

	rm ${temp_file[i]}
done
